### ISSUE TITLE
Usage / dependency issue with Pkg in 0.7

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/Pkg.jl#337]
This issue originates from

https://discourse.julialang.org/t/problem-with-reassignment-of-uuid-when-a-package-is-registered/11422

In my case, the issue is that when I try to precompile a package like `ReduceLinAlg` in v0.7 I get an error because the package `Compat` cannot be found, which is a dependency required by another dependency, i.e. `Reduce`, which depends on `Compat`. Since `ReduceLinAlg` does not depend on `Compat` itself, there seems to be an issue with `Pkg` being able to find `Compat` for `ReduceLinAlg`.

```Julia
julia> using ReduceLinAlg
[ Info: Precompiling module ReduceLinAlg
ERROR: LoadError: ArgumentError: Module Compat not found in current path.
Run `Pkg.add("Compat")` to install the Compat package.
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:868
 [2] include at ./boot.jl:314 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1071
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope
 [6] eval at ./boot.jl:316 [inlined]
 [7] eval(::Expr) at ./client.jl:394
 [8] macro expansion at ./none:3 [inlined]
 [9] top-level scope at ./<missing>:0
in expression starting at /home/flow/.julia/dev/ReduceLinAlg/src/ReduceLinAlg.jl:4
ERROR: Failed to precompile ReduceLinAlg to /home/flow/.julia/compiled/v0.7/ReduceLinAlg/1Dbd.ji.
Stacktrace:
 [1] error at ./error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at ./loading.jl:1207
 [3] _require(::Base.PkgId) at ./loading.jl:1007
 [4] require(::Base.PkgId) at ./loading.jl:878
 [5] require(::Module, ::Symbol) at ./loading.jl:873
```

@ScottPJones also has a similar issue, I believe.

**Comment by fredrikekre** [comment]
If you want to do [`using Compat`](https://github.com/JuliaReducePkg/ReduceLinAlg.jl/blob/1b89cd5db31116182dbb11a7714cce8bb49da9c4/src/ReduceLinAlg.jl#L4) you need to depend on it: https://github.com/JuliaReducePkg/ReduceLinAlg.jl/blob/1b89cd5db31116182dbb11a7714cce8bb49da9c4/REQUIRE

**Comment by chakravala** [comment]
So it's no longer enough that `Reduce` has `Compat` in its REQUIRE file? Are you implying that there is a fundamental change in the package management system, so that I now have to specify all the requirements of all the required packages?

**Comment by KristofferC** [comment]
Yes, you have to specify the packages you depend on. There is good justification why in the code loading section in the docs.

**Comment by KristofferC** [comment]
It is resolved, you need Compat in REQUIRE if you want to use Compat.

**Comment by chakravala** [comment]
Hm... that seems like it could get tedious, especially when you have packages that depend on packages that depend on packages, it could get very tedious to manually look them all up in the future. Is there any plan for having the package manaager automatically handle this in future? Where exactly is the section in the docs, could you link it?

**Comment by KristofferC** [comment]
> you have packages that depend on packages that depend on packages

You only need to add the packages you depend on, not recursively what your dependencies depend on. That is up to them to declare. You need to declare all packages you want to `using` or `import` in your package, no more.

**Comment by chakravala** [comment]
Oops, I forgot that I had `using Compat` in there, thought it was only depending on it recursively.

**Comment by chakravala** [comment]
Tried it again, after adding it to REQUIRE, but I still get the same error.

**Comment by KristofferC** [comment]
> Although, in the previous package manager, there wasn't an error.

We have fixed that now :)
